### PR TITLE
feat: neural tangents support

### PR DESCRIPTION
**Pull request by kjappelbaum**
- [X] Breaking change (fix or feature that would cause existing functionality to change)

BREAKING because it drops Python 3.6 support 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation
- [ ] Developer tools
- [ ] Refactoring
- [ ] Test

## Actions (for code changes)

- [X] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by kjappelbaum** [comment]
Features I still need to look into 

- [ ] vectorize/parallelize the inference and the _set_data operations
- [ ] give the option to train an ensemble of finite width models 
- [ ] automatically standardize the `X` and `y`  (this should probably happen in `set_data` as, if we would do it only in the beginning, it would mess up things if we use the `augment` function) 
- [ ] write docs, particularly how to stabilize the predictions

**Comment by kjappelbaum** [comment]
somehow the predictions are still a bit off
Screen Shot 2020-11-23 at 16 28 20

**Comment by kjappelbaum** [comment]
ok, one key to making it work was to change the standard deviations of the initialisation.

**Comment by kjappelbaum** [comment]
So, I decided to move the finite width ensemble to its own module. To make it interoperable with the infinite width cases, we will use the same dataclass but the train logic (and required inputs such as the optimizer) are sufficiently different to create a new class for this case

**Comment by kjappelbaum** [comment]
what i also notice is that we will need to drop Python 3.6 support if we use `dataclasses`

**Comment by kjappelbaum** [comment]
@byooooo I think this is now ready for review and, again, should be squashed before merging. 

Important points: 
- Introduces support for NNTK, NNGP built with the neural tangents library and deep ensemble using JAX 
- This PR drops Python 3.6 support (as `dataclasses` would need to be backported) 
- The core operations are implemented as pure functions, to make it easier to parallelize them in a later PR (I do not want to do this now, because we should test/debug the serial code first before we implement something in parallel) 
- Both new classes are constructed with sequences of custom datamodels. The reasoning behind choosing this approach is that it is easier for us to access the relevant functions and later also easier for the user to aspect different aspects of the model. 
- Both new classes will be also exposed at the top level of the package (as the other PAL classes) 
- Please check if the API/naming makes sense to you 
- The behavior of the new classes is different from the old ones in the sense that they automatically scale the features and objectives

I didn't add much background discussion to the docs so far, only mention the new classes in "Getting Started" and link to some references. Potentially, we could also add some notebooks with tutorials with the new classes. 

Other changes: 
- Reorganized the extras in the `setup.py` such that we have an `all` option, which we also use for the CI

**Comment by kjappelbaum** [comment]
if we want to improve coverage, we could do it in `validate_inputs`, e.g., the positivity check for sequences is not run

**Review by byooooo — APPROVED** [review]
looks fine with me. i guess we will remove python 3.7 support?

**Comment by kjappelbaum** [comment]
>i guess we will remove python 3.7 support?

This PR should only remove 3.6 support. If you think it is important, we can backport the dataclasses

**Comment by byooooo** [comment]
oops yea i meant 3.6. yea i would if it's not too much work, since i think people still tend to use it and we don't want to exclude them

**Review by byooooo — COMMENTED** [review]
looks good

**Pull request merged**
